# Description: Allow Enderman to pickup block.
# Default: false
allowEndermanToPickup = false
# Description: Enderman will not attack you as long as you haven't attacked them
# Default: false -> mean it's like vanilla minecraft
disableEndermanFromAttackingFirst = false
# Description: Enderman will no longer can teleport
# Default: false -> mean it's like vanilla minecraft
disableEndermanFromTeleporting = false
# Description: Allow you to customize the distance when an Enderman is teleported randomly. You can set a minimum value and a maximum value (always greater than 0)
# Default: false -> mean it's like vanilla minecraft
enableTeleportationDistance = true
teleportationDistanceXMin = 100
teleportationDistanceXMax = 1000
teleportationDistanceYMin = 100
teleportationDistanceYMax = 1000
teleportationDistanceZMin = 100
teleportationDistanceZMax = 1000